import type { Book, Profile, PurchaseRequest } from "./types";

export const departments = [
  "全部科系",
  "資訊工程學系",
  "企業管理學系",
  "外國語文學系",
  "電機工程學系",
  "通識教育中心",
];

export const demoProfiles: Profile[] = [
  { id: "seller-1", name: "陳學姊", email: "senior@example.edu", department: "資訊工程學系" },
  { id: "seller-2", name: "林學長", email: "lin@example.edu", department: "企業管理學系" },
  { id: "seller-3", name: "王同學", email: "wang@example.edu", department: "外國語文學系" },
  { id: "demo-user", name: "陳小明", email: "student@example.com", department: "資訊工程學系" },
];

export const demoBooks: Book[] = [
  {
    id: "book-1",
    sellerId: "seller-1",
    title: "資料結構：使用 C++",
    author: "Michael T. Goodrich",
    isbn: "9789863124568",
    department: "資訊工程學系",
    course: "資料結構",
    teacher: "李大華",
    edition: "第 2 版",
    condition: "近全新",
    price: 420,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=800&q=80",
    meetup: "圖書館一樓",
    description: "只有前兩章有少量螢光筆記，無缺頁，附上課整理的小抄。",
    status: "available",
    createdAt: "2026-06-08T10:00:00.000Z",
  },
  {
    id: "book-2",
    sellerId: "seller-2",
    title: "管理學：理論與實務",
    author: "Stephen P. Robbins",
    isbn: "9789863414218",
    department: "企業管理學系",
    course: "管理學",
    teacher: "張雅雯",
    edition: "第 8 版",
    condition: "有筆記",
    price: 350,
    imageUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=800&q=80",
    meetup: "管理學院中庭",
    description: "重點章節有完整筆記，適合期中期末快速複習。",
    status: "available",
    createdAt: "2026-06-07T08:30:00.000Z",
  },
  {
    id: "book-3",
    sellerId: "seller-3",
    title: "English Grammar in Use",
    author: "Raymond Murphy",
    isbn: "9781108457651",
    department: "外國語文學系",
    course: "英文文法與寫作",
    teacher: "Sarah Chen",
    edition: "5th Edition",
    condition: "書況良好",
    price: 280,
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80",
    meetup: "外語學院咖啡廳",
    description: "習題約完成三分之一，答案保持乾淨，可正常使用。",
    status: "negotiating",
    createdAt: "2026-06-05T14:20:00.000Z",
  },
  {
    id: "book-4",
    sellerId: "demo-user",
    title: "線性代數及其應用",
    author: "David C. Lay",
    isbn: "9789862803990",
    department: "電機工程學系",
    course: "工程數學",
    teacher: "黃志明",
    edition: "第 5 版",
    condition: "近全新",
    price: 500,
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=800&q=80",
    meetup: "電資大樓穿堂",
    description: "買來後只翻過幾次，書況接近全新。",
    status: "available",
    createdAt: "2026-06-04T09:00:00.000Z",
  },
];

export const demoRequests: PurchaseRequest[] = [
  {
    id: "request-1",
    bookId: "book-4",
    buyerId: "seller-2",
    message: "學長你好，我下學期會修這門課，這週三中午方便面交嗎？",
    status: "pending",
    createdAt: "2026-06-08T13:30:00.000Z",
  },
];
